name: Run Tests Workflow
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    environment: test
    strategy:
      matrix:
        node_version: [20.x]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{matrix.node_version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://npm.pkg.github.com'
      - run: echo REACT_APP_NODE_ENV=test >> ./.env
      - run: echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> ./.env
      - run: echo STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }} >> ./.env
      - run: echo JWT_SECRET=JWT_SECRET >> ./.env

      - run: echo "registry=https://registry.yarnpkg.com/" > .npmrc
      - run: echo "@internxt:registry=https://npm.pkg.github.com" >> .npmrc
      # You cannot read packages from other private repos with GITHUB_TOKEN
      # You have to use a PAT instead https://github.com/actions/setup-node/issues/49
      - run: echo //npm.pkg.github.com/:_authToken=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .npmrc
      - run: echo "always-auth=true" >> .npmrc

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test:cov
