name: 'Closing inactive PRs'

on:
  schedule:
    - cron: '0 7 * * *' # ~8 AM Spanish time (CET/CEST)
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark/close stale PRs
        uses: actions/stale@v9
        with:
          days-before-pr-stale: 15
          days-before-pr-close: 30
          stale-pr-message: |
            ⚠️ This pull request has been marked as stale due to 30 days of inactivity. 

            It will be automatically closed in 7 days if no further updates are made.
          close-pr-message: |
            ❌ This pull request has been automatically closed due to prolonged inactivity.
          stale-pr-label: 'stale'
          close-pr-label: 'auto-closed'
          exempt-draft-pr: true
          exempt-pr-labels: 'dependencies,blocked'
          ascending: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
